### PR TITLE
Add issue template for suggesting a new data source

### PR DESCRIPTION
**Pull request by JackGilmore**
## Description
Related to #103. Adding a new issue template for users to suggest a new data source

## Motivation and Context

Provides a common template for users to suggest data portals that we can scrape and aggregate onto opendata.scot. Paves the way to use this template to provide a more user friendly and anonymous Google form for non-GitHub familiar users to use as detailed in #104.

## How Has This Been Tested?

N/A - Can't really test these things until they're merged into the main branch. Follows the same format as existing issue templates in the [.github](https://github.com/OpenDataScotland/.github/tree/main/.github/ISSUE_TEMPLATE) repo.

## Screenshots (if appropriate):
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by KarenJewell** [comment]
Needs
- organisation name
- portal/ data SITE link (not files, to the site where the download button is"
- any useful info, e.g. how to tackle to scrape, or if there was previous convo etc.

That's enough for us to go really

**Comment by KarenJewell** [comment]
Ignore my last comment, I thought I was in an issue not a PR 🤦‍♀️

I would remove licensing section - licensing is per dataset not per publisher.

Type of organisation not useful... what might be useful to ask for though is a link to the organisation website so we can extract org contact details (in case it's not the same site).

for the url, please add specification that it must be a url to the interfacing WEBPAGE the data is downloaded from, it must not be a url to a file itself. 

Should we also add a dedicated "new source" or "add source" issue label

**Comment by JackGilmore** [comment]
> Ignore my last comment, I thought I was in an issue not a PR 🤦‍♀️
> 
> I would remove licensing section - licensing is per dataset not per publisher.

Would disagree on that. Knowing what licenses are used would help as assess if the data published is _actually_ open data or whether it's a split of open/non open data. This information could then help us assess the priority of getting that source added to our pipeline if we had lots of new source tickets open as there would be more value adding one with 100% open data vs a 50/50 split IMO.

> Type of organisation not useful... what might be useful to ask for though is a link to the organisation website so we can extract org contact details (in case it's not the same site).

We do store organisation type on JKAN so I would say it is useful! Sometimes it's not always apparent what type of organisation we have and it requires a bit of digging and research to find this out. If the submitter could supply this for us then it could make life a lot easier.
carbon

> for the url, please add specification that it must be a url to the interfacing WEBPAGE the data is downloaded from, it must not be a url to a file itself.

Agreed.

> Should we also add a dedicated "new source" or "add source" issue label

Was thinking that as I was creating this template. Sounds like a good idea.

**Comment by KarenJewell** [comment]
Just feels like a lot of burden on the reporter when most of the investigation needs to be done at the time of build anyway.

**Comment by KarenJewell** [comment]
Sorry, i'm being dumb. I didn't check for changes before merging.

**Comment by JackGilmore** [comment]
All good. I fixed it in 7684fa61f03af749429971159f119bd14099258d and then moved the issue template to actually live in the correct folder in cf76179cb4f177a2f8cfeeda8b4f65b41ce7b6f0 🤦‍♂️

**Pull request merged**
