### PR TITLE
Alternative NLS scraper

### PR DESCRIPTION
**Pull request by nutcracker22**
notes about this scraper:
- it only scrapes the webpage and does not touch the downloadable csv.
- I split up the long fetch_page_data function, but kept as much of the code as I could.
- some of the functions return lists, instead of strings (in case there is more than one license, or more than one file type), since I think lists are easier to handle later on. But this can be changed, if required.
- it runs without throwing errors (at least for me).
- the names of the datasets sometimes differ between csv and webpage. But one gets the content from both, I think.
- in the csv each dataset has a publication date in the format dd/mm/yyyy, but on the data pages, at most the publication year is present, but often even not that.
- file types given by the new scraper are not in standard format, yet. But probably this can be adopted, if I know what the standard is.

My questions (since I am both new to coding and collaborating):
- is the style of code what you would expect?
- is the way of writing the code in line with the project standards (are there any)?
- are there parts (comments, explanations, ...) missing in the code?
- should I use both the csv and the data pages to have more information available (so far this seems to affect only the publication date)?
- regarding file types and licenses, issue #105 seems to be a good source of information.

### CODE REVIEW

**Comment by ormiret** [comment]
Sorry, I meant to have a look at this last week, but got sidetracked before I did...

This looks good to me. 

Couple of places you have the pattern of creating an empty list and then a for loop appending things to it - list comprehensions can be more concise for that. 

For example the loop in `fetch_category_links` can be replaced with:
`list_of_links = [dropdown_item.find("a").get("href") for dropdown_item in dropdown_list]`
 
Where list comprehension or for loop is better is a bit personal preference (I tend towards abusing list comprehensions). 

I also had a go at reworking `fetch_licenses()`. There I'd use walrus operator to combine assigning to `figures` with checking it's value, both `None` and `[]` are falsey so don't need to compare to them directly, and then list comprehension to actually build the list:
``` 
def fetch_licences(page):
    if not (figures := page.find_all("figure", class_="wp-block-image is-resized")):
        if not (figures := page.find_all("figure", class_="wp-block-image size-medium is-resized")):
            if not (figures := page.find_all("figure", class_="wp-block-image size-large is-resized")):
                return []
    return [tidy_licence(f.find("a").get("href")) for f in figures]
```

I left out the docstring and debug output there, but could put them back. On those: your docstrings (and type annotations) don't match the code in a few places, looks like you moved to passing `BeautifulSoup` objects to a bunch of the functions but docstrings and type annotations still say they take `str`. 

You've got quite a lot of debug `print` calls: would be good to move them to go via `logging` to separate debug info from higher level info that would be useful to see from normal runs or errors.  https://docs.python.org/3/howto/logging.html#basic-logging-tutorial

**Comment by nutcracker22** [comment]
@ormiret: thanks for the comments and suggestions. They've been pretty helpful. I will go through the logging tutorial soon, and I have included the mentioned list comprehension, the `fetch_licences()`, and corrected the type annotations to `BeautifulSoup` objects.
The other for loops I have kept, so far, since I find that the code would become less understandable and by this less maintainable if I change them. But I am open to any suggestions.

**Review by KarenJewell — APPROVED** [review]
Yikes, sorry it's taken us so long to get to this.

I'm not sure I agree with the changes to licences in mergedata.py (the 2 of the 3 new ones aren't actually licences?) But I'm not going to hold the PR back for it - we can address them in a future iteration anyway to make it clever-er rather than having to manually list each variation of a licence (e.g. consistent casing).

Thanks very much for your help on this! Happy to merge. 
Checked:
- Script is already called in Github Actions 
- Output is already handled in mergedata.py
- no additional package dependencies needed for GH Actions

**Comment by nutcracker22** [comment]
@KarenJewell: I'm working on improving the license part.

**Pull request merged**
