### PR TITLE
update tidy_licence function

### PR DESCRIPTION
**Pull request by nutcracker22**
Updated the tidy_licence function in merge_data.py, based on the current merged_output_untidy.csv and the changes to the NLS licence treatment #133.
Applied case insensitive string comparison and stripping a string off (leading or) trailing "/", since there is no common approach in the datasets regarding the question whether the provided URL to the licence ends with "/" or not.

This is the continuation of the closed PR #128 .

### CODE REVIEW

**Comment by nutcracker22** [comment]
btw, I checked the "Open Government" licence, which also shows up on [https://opendata.scot/analytics/licensing/](https://opendata.scot/analytics/licensing/). The link on the pages containing this licence leads to "Open Government Licence v3.0", so I mapped is respectively.

**Comment by KarenJewell** [comment]
This looks good. Checking impact of change produces

> License check output is in the format: \<New value\> [\<Old values\>]
Open Government Licence v3.0 ["Open Government Licence 3.0 (United Kingdom)", "uk-ogl", "UK Open Government Licence (OGL)", "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/", "OGL3", "Open Government"]
Open Data Commons Open Database License 1.0 ["Open Data Commons Open Database License 1.0", "http://opendatacommons.org/licenses/odbl/1-0/"]
Creative Commons Attribution 4.0 International ["Creative Commons Attribution 4.0", "https://creativecommons.org/licenses/by/4.0/legalcode", "https://creativecommons.org/licenses/by/4.0/", "https://creativecommons.org/licenses/by/4.0"]
Public Sector End User Licence (Scotland) ["Public Sector End User Licence (Scotland)"]
No licence ["nan"]
Custom licence: other-closed ["other-closed"]
Custom licence: Other (Not Open) ["Other (Not Open)"]
Public Domain ["Other (Public Domain)", "https://creativecommons.org/publicdomain/mark/1.0/"]
Open Government Licence v2.0 ["http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"]
Creative Commons Attribution Share-Alike 3.0 ["https://creativecommons.org/licenses/by-sa/3.0/"]
No Known Copyright ["http://rightsstatements.org/vocab/NKC/1.0/"]
Non-Commercial Use Only ["https://rightsstatements.org/page/NoC-NC/1.0/"]
Creative Commons CC0 ["https://creativecommons.org/share-your-work/public-domain/cc0"]


But, I think you need to have a look into `license_link():` in [export2jkan.py](https://github.com/OpenDataScotland/the_od_bods/blob/main/export2jkan.py)  also to see what the end result is going to be and how that's going to interact with what you've done here (it's really not intuitive, I realise).

Some history might explain this. When we first started, we were just writing outputs to .csv so the named licences were fine. But when we introduced the JKAN frontend, JKAN itself **uses** URLs in [licenses.yml](https://github.com/OpenDataScotland/jkan/blob/gh-pages/_data/licenses.yml) to identify the label for display. It's madness I know - we're going _URL > Label > URL > Label_ again in _scraper > merge_data.py > export2jkan.py > jkan_

So what that means is, what you have now as `Creative Commons Attribution 4.0 International` in merge_data.py won't pick up in export2jkan.py because it's not one of the 3 commons or 5 OGL labels. So instead of returning `https://creativecommons.org/licenses/by/4.0/` it will return `unknown` at export2jkan.py which means when it gets to `licences.yml` it's just going to return a `blank`. See [this example](https://opendata.scot/datasets/aberdeenshire+council-adopted+core+paths/) of what it looks like when published to site.

So, sincerely sorry for the labyrinth. 
I think the short-term solution here is: 
1. update export2jkan.py with the new labels you're creating in merge_data.py
2. update licenses.yml with URLs if there are any new valid ones to add.

The long-term solution is to resolve issue #163 which will make merge_data.py and export2jkan.py redundant anyway.

**Comment by nutcracker22** [comment]
yep, when looking at the code I recognised that there's a lot of back and forth ;) I changed export2jkan.py, and because there are more licences now, I basically used the same code as in merge_data.py, just with keys and values switched. The console log when running export2jkan.py looks good, and I also checked some (but not all ;) ) datasets in jkan/_datasets/. Licences show up as expected.

**Comment by KarenJewell** [comment]
Delighted with this - thanks very much @nutcracker22! It looks like there is a bug in JKAN frontend related to display but it's naught to do with this processing. Merging.

**Comment by JackGilmore** [comment]
Sorted the licence display on the frontend. `licenses.yml` uses the licence URL as a key when matching licence names. This causes a mismatch when the URL we're saving is HTTP but the link in the `.yml` file is HTTPS. I've updated all the links to be HTTPS in the following commits:
https://github.com/OpenDataScotland/the_od_bods/commit/b6bdb93ffda423b86ecb546d191d04052bae35a1
https://github.com/OpenDataScotland/jkan/commit/2510ab19b5f544cdaedd5447551880af8b5cfa7f

**Comment by nutcracker22** [comment]
@JackGilmore: sorry, I thought I had applied this change, since I did test for every http link, whether the https version works, as well. Thanks for sorting this out :)

**Pull request merged**
