### PR TITLE
55 enhance info for file links

### PR DESCRIPTION
**Pull request by KarenJewell**
## Description
This PR changes the display of asset links in the dataset pages. Where currently it shows the file extension only, we'll now show the filename if one has been provided by the publisher, it will still show the file extension (filetype) if there is no known filename.

Made changes to the usmart.py scraper also to return these needed filenames.
- ckan [was done before](https://github.com/OpenDataScotland/the_od_bods/commit/6717d6bd321db4a64e1e7799c032d50dba0fcc0e)
- arcgis and dcat don't seem to provide filenames, 
- sparkql_statistics looks incomplete anyway so I abandoned that one.
- The only other ones maybe worth updating are the web_scrapers.

## Motivation and Context
Addresses issue #55 

## How Has This Been Tested?

Ran ckan.py and usmart.py locally, checked their csv output. Ran merge_data.py and export2jkan.py and checked their outputs too. Main point of check was that "File Name" in merge_data.csv and resources/name in JKAN dataset files are as expected.

Can't test JKAN locally.

help.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [N] My change requires a change to the documentation.
- [N] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by KarenJewell** [comment]
I need to wait a couple weeks to test this but will get to it. This has been helpful so far: https://jekyllrb.com/tutorials/using-jekyll-with-bundler/

**Comment by KarenJewell** [comment]
Tested with new docker container from https://github.com/OpenDataScotland/jkan/pull/6 instructions: https://github.com/OpenDataScotland/the_od_bods/wiki/How-to:-Run-frontend-locally and behaves as expected

Ready for review @JackGilmore

**Comment by JackGilmore** [comment]
image
Not sure why this is happening but when I run through all the scripts and create the `merged_output.csv` the header appears to split over multiple lines.

image
Not sure if it's linked but then I think the wrong categories are then getting written to JKAN and that also includes a blank one

**Comment by KarenJewell** [comment]
ahaha... hard reset the branch? or at the least delete `merged_output.csv` and rerun `merge_data.py`. Changes in this PR don't go so far upstream so that would seem to be an existing repo issue.

**Review by JackGilmore — APPROVED** [review]
Re-ran it with a less sleepy head and it's all working. Happy for this to go live and will leave for you to merge when you see fit ☺

**Pull request merged**
