### PR TITLE
tidy_licences

### PR DESCRIPTION
**Pull request by nutcracker22**
changed the function tidy_licence to avoid the need to manually list each variation of licences.

### CODE REVIEW

**Comment by ormiret** [comment]
I'm not sure about some of this...

I think too much is being processed to "No license". CC0 at least is definitely a license and I think better to keep that information. I don't think "public domain" and "no license" are really the same either. I'm also sceptical of the mapping of "No Known Copyright" to "No license" that was already there. 

I'm a bit worried about matching anything containing the key strings in case they match things that shouldn't ("ogl" would match "Google's evil proprietary license" and transform that into "Open Government Licence v3.0")

**Comment by KarenJewell** [comment]
@ormiret could you review and merge if ok please?

**Comment by nutcracker22** [comment]
@ormiret: I changed my initial way, because I probably misunderstood Karen's last comment on [Alternative NLS scraper PR 107  ](https://github.com/OpenDataScotland/the_od_bods/pull/107). I can apply the required changes to CC0, Public Domain and "No Known Copyright" easily. About "ogl", you're absolutely right about Google's evil license ;) However, 527 datasets from different sources return either "uk-ogl" or "OGL3" as licence (see [merged_output_untidy.csv](https://github.com/OpenDataScotland/the_od_bods/blob/main/data/merged_output_untidy.csv)). How about using these two strings, instead of only "ogl"?

@KarenJewell: aren't your last changes to the PR basically reverting everything back to the current [main branch](https://github.com/OpenDataScotland/the_od_bods/tree/main)?

**Comment by KarenJewell** [comment]
@nutcracker22 haha yes I did think that too, but once the changes for the other functions not to do with licences were removed and the string matching removed (agreed with @ormiret), there was not much left. The NLS scraper was also included in the original commits but again once the relevant edits were isolated it ended up having little left, except in its place is a fix for #133 relevant to licences.

Perhaps a potential improvement to keep with the original scope (and my comment in PR107) is to same-case both the keys and the data value to compare - rather than changing the stored keys themselves. The licenses come pretty standard so I am reluctant to change those. See https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

@ormiret's point about 

> I'm also sceptical of the mapping of "No Known Copyright" to "No license" that was already there. 

is still open - what is the proposed change? Retain "No Known Copyright"?

Ultimately, any change should consider what the end impact on the user is - let's keep variation on the displayed licences as light as possible. It's challenging enough for us!

**Comment by nutcracker22** [comment]
@KarenJewell: I just committed an updated version of the tidy_licences function. It should keep the old key-value combinations, but removed some of the variations, as you suggested in [this comment](https://github.com/OpenDataScotland/the_od_bods/pull/107#pullrequestreview-1048534320).
In case I overlooked something, just let me know. And I hope it addresses all problems you two mentioned ;)

**Comment by ormiret** [comment]
I'm not keen on the "license contains key" approach. I don't think we can come up with a set of keys that will match what we want without (potentially) having spurious matches. 

"cco" that's there at the moment matches 113 words in `/usr/share/dict/words` on my system and we can't guarantee that no one is going to use one of those words in the name of a license (or any other word that contains one of the other keys).

Even for the more complicated keys (like the URL based ones) I don't think we can match on that existing within the license string we have for a dataset. I have seen (though not sure if we're pulling in any of them yet) license strings along the lines of "OGL3 except location data that came from $GIS_SYSTEM and is under $OTHER_LICENSE" and we shouldn't collapse that to just OGL3.

**Comment by nutcracker22** [comment]
okay, it seems that it automatically closed this PR when I synced my main branch with that of OpenDataScotland. I will try to tidy the tidy_licence function by keeping the current approach, and then create a new PR.

**Comment by ormiret** [comment]
Switching the comparison to be case insensitive should give a bit of clean up, looking forward to seeing if you can find any other improvements.

Thanks for looking at this @nutcracker22

**Pull request closed without merging**
