### PR TITLE
Issue 105: Tidy filetypes for datasets

### PR DESCRIPTION
**Pull request by nutcracker22**
Please do not merge, unless it really solves #105.

### CODE REVIEW

**Review by KarenJewell — CHANGES_REQUESTED** [review]
merge_data.py Ln 721: Could we remove the prefix "Custom file type:" please? 

I know we use this in Licences, but I don't think the same context applies here. There are a small set of known and valid licences so we want to control and correct its display. But filetypes really can go quite varied and are still valid even if we've not encountered them yet.

**Comment by KarenJewell** [comment]
Just wanted to say I haven't been ignoring this - I am partway through checking the impact of this change

**Comment by nutcracker22** [comment]
> merge_data.py Ln 721: Could we remove the prefix "Custom file type:" please?
> 
> I know we use this in Licences, but I don't think the same context applies here. There are a small set of known and valid licences so we want to control and correct its display. But filetypes really can go quite varied and are still valid even if we've not encountered them yet.

Valid point. I just did a push.

Shall I also replace the `__contain__` method, as discussed in #128? I tend to do so, since I need to add some file types, and then there are a couple of file types which would be difficult to map properly otherwise (e.g. "doc", "docx", "document link").

**Comment by nutcracker22** [comment]
I did a commit to add missing file types according to the current merge_output_untidy.csv and thus also removed the `__contains__()` function. In case you do not like these changes, I can easily revert them.

**Review by KarenJewell — APPROVED** [review]

**Comment by KarenJewell** [comment]
Looks good to me! Happy to close

Quick check on impact of change:
```
import pandas as pd
o_data = pd.read_csv('data/merged_output_untidy.csv')
c_data = pd.read_csv('data/merged_output.csv')
t_data = pd.DataFrame({'org':o_data['FileType']
                        ,'new':c_data['FileType']})
t = t_data.drop_duplicates().reset_index()
n_list = t['new'].drop_duplicates()
n_list

for r in n_list:
    print(r, t[t['new']==r]['org'].to_list())
```
produces changes in format: New Label [Old Labels]

> MS EXCEL ['XLSX', 'XLS', 'vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'vnd.ms-excel']
CSV ['CSV', 'csv']
No file type [nan]
HTML ['HTML', 'html']
ARCGIS GEOSERVICE ['Esri REST', 'ArcGIS GeoServices REST API', 'ArcGIS GeoService']
GEOJSON ['GeoJSON', 'GEOJSON']
KML ['KML']
ZIP ['ZIP', '.zip', 'zip']
PDF ['PDF', 'pdf']
URL ['web', 'url', 'uk/data/#tabgb1900', 'uk/roy/gazetteer/#download ']
WMS ['WMS']
WFS ['WFS']
XML ['XML', 'xml']
JSON ['JSON', 'json']
ATOM FEED ['Atom Feed']
Image ['JPEG']
XPS ['XPS']
KMZ ['KMZ']
QGIS Shapefile ['QGIS']
7-Zip compressed file ['application/x-7z-compressed']
TXT ['TXT']
FEATURE LAYER ['Feature Layer']
TABLE ['Table']
WEB MAP ['Web Map', 'Web Mapping Application']
HUB SITE APPLICATION ['Hub Site Application']
FORM ['Form']
DOCUMENT LINK ['Document Link']
IMAGE ['Image']

**Pull request merged**
