### PR TITLE
Angus council link 99

### PR DESCRIPTION
**Pull request by nutcracker22**
## Description
Implemented replace() in ckan.py to replace `http:` with `https:` to solve OpenDataScotland/the_od_bods#99 
@JackGilmore: did you mean something like this as solution?

## Motivation and Context
See OpenDataScotland/the_od_bods#99 

## How Has This Been Tested?

- ran ckan.py and checked Angus Council.csv
- I couldn't check by requesting each asset URL, because I guess they temporarily blocked my IP because of the many requests :D

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nutcracker22** [comment]
Just a side note: when I wanted to write a file to automatically test my changes (=request all the changed links), I recognised that the special characters `\r` and `\n` cause a problem when parsing the [Angus Council.csv](https://github.com/OpenDataScotland/the_od_bods/blob/main/data/ckan/Angus%20Council.csv). It is not the first time, that I encounter such a problem. Of course, I could write a work around, but regarding #182, I tend to clean all incoming data right at the beginning.

**Comment by nutcracker22** [comment]
okay, when manually testing the URLs, I recognised, that for some the http worked, but the https would not work. So I implemented requests to check for the accessibility. If https is not available, the http URL is kept.

Will try to refactor it tomorrow, to do the https request first (if this request works, the http request can be skipped).

**Comment by JackGilmore** [comment]
From the looks of it, opendata.angus.gov.uk will only serve over HTTP which is where the mixed content issue is coming from. If you try to force HTTPS then it just doesn't connect at all. 

All the GIS-based ones that used data.angus.gov.uk appear to be fine. You can use HTTPS or HTTP redirects to HTTPS anyways from the looks of it. I've dropped an email to the contact link in the about page on their CKAN page to see if they could apply an SSL cert so that HTTPS works on their CKAN instance. If that fails then we might have to look at other solutions such as:
- Putting a message telling users they'll need to copy the link and open it in another tab/window to download (easy)
- Proxy the requests through a server that downloads the content and serves it up via HTTPS (hard)

**Comment by nutcracker22** [comment]
did you get any response @JackGilmore?

**Comment by JackGilmore** [comment]
@nutcracker22 I sent through a chaser message via the council's general enquiry last Friday. If no response by this Friday 18th then I've got another contact @watty62 gave me that I can try emailing direct.

**Comment by JackGilmore** [comment]
Apologies. I kind of dropped the ball on this one by forgetting to send that email. I've sent it now so I propose we wait until the end of next week to see if we get any form of response.

Given the difficulty we've had getting anyone from Angus to speak to us, I'm thinking it's unlikely we'll get any form of a response or action from them on this issue. What I'm thinking is we put some sort of workaround where we display a modal message when a user clicks on a non HTTPS link saying something to the effect of "We can't link you directly to this content because it's not served over HTTPS. Please copy and paste this link into a new browser window: http://example.com"

**Comment by JackGilmore** [comment]
Yet again I'm lacking in my duties in keeping up with GitHub issues. I did get a reply shortly after emailing my contact in Angus Council. In short, it doesn't look like it's going to be fixed anytime soon.

My thoughts are that we replace the HTTP links with HTTPS where they'll work and then we display a modal message for any leftover HTTP links like I [mentioned above](https://github.com/OpenDataScotland/the_od_bods/pull/201#issuecomment-1326825484). What do you think @nutcracker22?

**Comment by JackGilmore** [comment]
Closing this PR as unmerged as we've resolved and mitigated this issue with merging in https://github.com/OpenDataScotland/jkan/pull/38

**Pull request closed without merging**
