### PR TITLE
CKAN and statistics.gov.scot bug fixes

### PR DESCRIPTION
**Pull request by JackGilmore**
Fixed a couple of issues I noticed when looking through the site:

- CKAN
    - Added in some alternative props for file size and file type
    - Removed the encode/decode for dataset description - seems to work fine now?
- Statistics.gov.scot
    - 2 of the datasets weren't getting populated with an owner. I've added in a fallback value to try another column and then if that fails then it'll fallback to a hardcoded value of "Scottish Government"
- merge_data.py and export2jkan.py
    - The file name column was in the wrong place meaning that some columns were being picked up incorrectly when exporting to JKAN
    - The date created column wasn't getting parsed or formatted during the merge process

### CODE REVIEW

**Comment by JackGilmore** [comment]
> I'm having trouble locally with CKAN on URL `https://www.opendata.nhs.scot//api/3/action/package_show?id=allied-health-professionals-musculoskeletal-waiting-times ` Error:
> 
> > File "...the_od_bods/processor.py", line 39, in get_json
> > return json.loads(request.urlopen(req).read().decode())
> > [truncated]
> > urllib.error.URLError: <urlopen error [Errno 22] Invalid argument>
> 
> but URL looks valid to me. All other CKAN URLs are fine and the first 3 of PHS datasets are fine till it hits this one, any thoughts?
> 
> > Processing https://www.opendata.nhs.scot/
> > Found 90 datasets
> > https://www.opendata.nhs.scot//api/3/action/package_show?id=18-weeks-referral-to-treatment
> > https://www.opendata.nhs.scot//api/3/action/package_show?id=27-30-month-review-statistics
> > https://www.opendata.nhs.scot//api/3/action/package_show?id=alcohol-related-hospital-statistics-scotland
> > https://www.opendata.nhs.scot//api/3/action/package_show?id=allied-health-professionals-musculoskeletal-waiting-times <<< fails while processing this one

Works on my machine 😅 (Running Ubuntu via WSL and using Python 3.9). 

That looks to be an IO error strangely? I take it that it's reproducible on your machine? Can you access that last URL in your browser with no issues? If it's still happening maybe try deleting the existing CSVs and starting from an empty folder?

**Comment by KarenJewell** [comment]
It's moved on. Same error at different point, so it's not url specific.
Tried deleting output .csv - no change.
Feels like something needs to be closed?

**Review by KarenJewell — CHANGES_REQUESTED** [review]
ckan.py line 73:
needs that `.encode('unicode_escape').decode()` reinstated for `description`, there are unescaped characters breaking the PHS dataset.

**Comment by KarenJewell** [comment]
Resolved my `urllib.error.URLError: <urlopen error [Errno 22] Invalid argument>` problem. 
No idea what caused it, but turning my VPN on resolved it. mad. 
May have been an IPv6 connection setting on my machine https://stackoverflow.com/questions/46942585/pip-error-oserror-errno-22-invalid-argument

If we can make my one change request then I'm happy to merge PR.

**Comment by JackGilmore** [comment]
> ckan.py line 73: needs that `.encode('unicode_escape').decode()` reinstated for `description`, there are unescaped characters breaking the PHS dataset.

Looks like this is more an issue to do with how the CSV is getting written rather than the character encoding. The `write_csv` method is using `csv.QUOTE_MINIMAL` which doesn't seem to wrap the description field with double quotes if it contains a new line character. 

Changing to `csv.QUOTE_NONNUMERIC` seems to fix it but has the knock on effect of wrapping quotes around everything non-numeric (like it says on the tin 😉). I'd be hesitant to make that change though without checking all the other scripts. Maybe we add a parameter to the `write_csv` method to choose what quoting method gets used, although that doesn't help when it comes to merging all the data together... :/

**Comment by gavbarnett** [comment]
Maybe CSV are not the answer? Seems like we've got a few issues with encoding, line endings, quoting, arrays...

I'd suggest a more structured and flexible format like JSON? (Not just now perhaps but one for the future)

**Comment by JackGilmore** [comment]
I did think about this a while ago but I have a feeling I shelved it because I had reservations over switching to JSON as I thought it would be less user-friendly to entry-level contributors compared to the standard tabular format of a CSV which can be opened and easily read by software on most computers (After all, it is also the most popular file type in resources on opendat.scot). 

I would agree now though and caveat my previous statement that using CSV as our standard file format when processing files appears to be causing us more grief than benefits compared to using another format like JSON. The majority of the API-based scrapes we do as well return JSON so it probably makes more sense to go JSON => JSON => YAML rather than JSON => CSV => YAML.

If we really want a CSV end result to publish on opendata.scot, we can always generate it as part of the site build, the same way that [datasets.json](https://opendata.scot/datasets.json) gets built up.

@KarenJewell - What's your thoughts?

**Comment by KarenJewell** [comment]
Completely agree. I'm sure @ormiret and @kymckay have said the same also. The csv store has served us well for a few hacks, but now the project is maturing it's sensible to consider better storage options (if we store the intermediary at all).

Agreed, the csv can and should be a published output from us, rather than input and output. 

Removing the csv middle storage layer doesn't have to impede entry-level contributors either. There's nothing stopping new contributors or new scrapers from still writing to outputs to csv at scraper level - we can supply a ready helper to write that csv's contents to our storage. Then when the scaper is more stable and mature, we can help the contributor wean it off the csv. 

However, this all smells like a separate issue, and so here's #163 

For this PR though, let's reinstate that change for now. We can apply the "proper" fix in a bit.

**Comment by JackGilmore** [comment]
@KarenJewell For the benefit of this PR I've patched the scraper to re-add the escaping for the problem portals (PHS, Stirling and Dundee). I also added in a temp patch to overwrite the dataset owners for PHS back to "Public Health Scotland" seeing as PHS use the CKAN owner/org field as a category rather than for organizations. The joys of the lack of standardization!

Latest commit may look like a lot of changes as I ran the script through black for formatting. It's all ready to be re-reviewed though.

**Comment by KarenJewell** [comment]
not sure I agree with org specific treatments, but it works.

**Comment by JackGilmore** [comment]
> not sure I agree with org specific treatments, but it works.

Temp patches for now really until we can move to JSON to sort character encoding and checking the dataset owner against the list of orgs we have on opendata.scot

**Pull request merged**
