### PR TITLE
Br adding tests for api scrapers

### PR DESCRIPTION
**Pull request by gavbarnett**
# Purpose

_(Resubmitting from branch - no changes from previous pull request other than branch name)_

This pull request is part of #122 - Add python tests

This pull request added a `tests` folder which contains basic `pytest` tests. Having tests allows for safer refactoring of code and easier long term maintenance (if well maintained and used).

Tests added for:

- processor.py
- arcgis.py
- dcat.py
- usmart.py
 
## Changes to api scripts for testing

Some minor changes were made to the above to allow for testing, but these have been as minimal as possible. These changes are either to adjust they way the processor.py file is accessed (depending on where the file is called from) or to allow tests to select specific functions and redirect to mocks

## Test styles & mocks

The tests are a mix of "A should do B" and "last time A did C so expect C". The former check the logic is sound, the later check for any changes. To accomplishes "last time A did C so expect C" style tests a mock folder is included with the json API responses from some of the projects sources, this means the source data is unchanging with time from the point of view of the test.

## 2 minor fixes are included:

- usmart.py urls contained spaces - 364238d93c89b27d969c068be5d56acda9d31054 
- processor.py added blank lines to csvs on windows - 7678f7df7ddfb7aa448057df37cb13c9dda0057d

## Testing Notes

A markdown file is included in the test folder to explain how to install pytest and the validators module. And then how to run and add more tests (for more details google `pytest`)

To run all tests open a terminal in the project root directory and simply run `pytest` as a command.

# Testing

All tests currently pass on my windows machine

### CODE REVIEW

**Comment by gavbarnett** [comment]
Note to the powers at be:

Accept https://github.com/OpenDataScotland/the_od_bods/pull/119 first (black formatting PR)
Then https://github.com/OpenDataScotland/the_od_bods/pull/117 (.append() PR) - hopefully no conflicts.
Then https://github.com/OpenDataScotland/the_od_bods/pull/127 will probably need me to update my branch before being accepted.

**Comment by ormiret** [comment]
I'm getting 3 failures when I run the tests:
```FAILED tests/arcgis_test.py::test_get_datasets - AssertionError: assert False
FAILED tests/dcat_test.py::test_get_datasets - AssertionError: assert False
FAILED tests/usmart_test.py::test_get_datasets - AssertionError: assert False
```
Failing on the `filecmp` assertion in each. I think the problem is unix vs DOS line endings. I'm running Linux (so likely to have the same problem in github action Linux container) git is translating the expected files to unix but `csv.writer` defaults to using DOS line endings on all platforms. 

I think best to make git stick to DOS line endings for these files with `.gitattributes` https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by gavbarnett** [comment]
Thanks, 
I'll need to be more careful checking on both Linux and Windows in future.

Is that something you need to change at a project level? I'm a bit unsure. Will have a read of that link.

**Comment by gavbarnett** [comment]
Just fixing the .gitattributes isn't going to fix the test on a personal Unix system though.... Will have a think.

**Comment by gavbarnett** [comment]
So line endings are an easy fix. 
In write_csv() i just need to add `lineterminator="/n"` when opening the file.

That solves the bug on usmart.

But there are other encoding issues (I've noticed double quotes is one) which need to be sorted too. Probably adding `encoding="utf-8"` in a few places wouldn't hurt. Will keep investigating.

**Comment by gavbarnett** [comment]
ok, I think I have a working fix in my BR-checking-linux-vs-windows-encoding branch. (the branch is a mess - was just using it for testing)

Will tidy up and update this branch. - I'll also expand the number of old/new comparison tests to cover more files.

**Comment by gavbarnett** [comment]
Fixed linux vs windows bugs with test 😄 

BUT... I've found another issue. 😢 
Because arcgis.py effectively uses a linked list of urls it's still going out to the web for data during the test. This is no good as the results can & do change! I need to work out a way to redirect this - shouldn't be too tricky but not one I'm going to solve tonight.

**Comment by gavbarnett** [comment]
> BUT... I've found another issue. 😢
> Because arcgis.py effectively uses a linked list of urls it's still going out to the web for data during the test. This is no good as > the results can & do change! I need to work out a way to redirect this - shouldn't be too tricky but not one I'm going to solve > tonight.

Solved the above. This PR should be ready to test again and hopefully merge into the project. :-)

My solution to this final issue is just to ignore the arcgis linked urls. This is not great but does allow the test to run. 
In future adding a separate specific test for the linked list urls would be good.

I tested it multiple times on linux (mint) and windows and both seem to work. 

Notes:
-  `generate_new_mock_data.py` should be run infrequently by maintainers only. The test data should be static unless there is a reason to update it. This script gets all the json output from the source api's and stores them along side the expected csv covered data.
   - In future this should be expanded to cover the html scrapers (outside scope of PR/branch)
- As before you just need to run `pytest` at root (optionally `pytest -v`) to run the test set.

**Pull request merged**
