### PR TITLE
 National Library Scotland Multiple Data Downloads #130 

### PR DESCRIPTION
**Pull request by nutcracker22**
Modified the scraper so that it treats each download as an asset and creates the respective entry in output_nls.py

### CODE REVIEW

**Comment by nutcracker22** [comment]
okay, the transition to multiple data downloads for the NLS scraper might be done. The output_nls.csv looks good, as well, after running this updated version. But someone else should also check it and let me know about things I've forgotten or should be changed.

**Comment by KarenJewell** [comment]
Magic! The individual asset links look great!

2 suggestions:
1. Do you want to go ahead and delete the old code snippets before I merge? And
2. The descriptions for all datasets are currently empty, could we add something please? For most of the datasets, the main body text is fine. For datasets with multiple assets, the asset descriptions would be great also.

**Comment by nutcracker22** [comment]
@KarenJewell 
I'll try to do this, but it will probably be a week or so till I get the time for.

**Comment by KarenJewell** [comment]
absolutely no rush at all - thanks very much for the help!

**Comment by nutcracker22** [comment]
@KarenJewell, can you take a look at it now, please? I don't know, why for some paragraphs it does these funny line breaks (there are no line breaks in the source html visible), while for others it doesn't break the lines.

**Comment by KarenJewell** [comment]
Looks grand! thanks again @nutcracker22. Agree the line breaks are a pain, we've got that same issue across all the sourcing scripts. But you're right, hopefully #182 and #163 will deal with it across the board.

**Pull request merged**
