### PR TITLE
 Add name conversion for publisher "Na h-Eileanan an Iar" to "Comhairle nan Eilean Siar" #164 

### PR DESCRIPTION
**Pull request by fozy81**
Fixes name conversion for publisher "Na h-Eileanan an Iar" to "Comhairle nan Eilean Siar" #164 

## Description

Add name conversion for publisher "Na h-Eileanan an Iar" to "Comhairle nan Eilean Siar" #164 

## Motivation and Context
Open issue

## How Has This Been Tested?
Not tested the change, unsure how to run tests locally.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (only if users are using `Na h-Eileanan an Iar` as a reference to query website)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by KarenJewell** [comment]
Thanks for this and the feedback @fozy81  - this rightly tells me our docs are not up to scratch!

Best way to test this now would be to:
1. Clear out the `data/` folder
2. run `python ckan.py` at root to get a fresh copy of ckan data
3. run `python merge_data.py` to execute change
4. check `data/merged_output.csv` for change. (the owner field should use the new name)

Have a look at requirements.txt for packages needed and main.sh for the complete process - I've only described an extract above. You could skip 1 and 2 and go straight to 3, but we know there can be issues working off the repo data so recommend fresh data for tests.

Alternatively, I'm on a train tomorrow so will write up new docs if you want to wait for that to trial it 😂

**Comment by fozy81** [comment]
@KarenJewell Thanks for your help, I'll give that a try over the weekend. :+1: :1st_place_medal:

**Comment by fozy81** [comment]
@KarenJewell  I've checked merged_output.csv for change. The owner field now matches the new name (Comhairle nan Eilean Siar).  :tada:

**Comment by KarenJewell** [comment]
Thanks for this @fozy81!

**Pull request merged**
