### PR TITLE
#180 added scottish forestry as a data source

### PR DESCRIPTION
**Pull request by marccodess**
## Description

Added Scottish Forestry as a data source via the ArcGIS API (Issue: [#180](https://github.com/OpenDataScotland/the_od_bods/issues/180)).

## Motivation and Context

Solves issue [#180](https://github.com/OpenDataScotland/the_od_bods/issues/180) by adding Scottish Forestry data to the Open Data Scotland project.

## How Has This Been Tested?

I did not find it necessary to run any pytest tests as I have not changed any syntax, just added a new API path. 

To test my changes I run the `arcgis.py` script generating the `scottish_forestry.csv` document consisting of the 19 new datasets. After running the `arcgis.py` script I run the `merged_data.py` script ensuring data was successfully parsed in the `merged_output.csv` output.

_I reverted changes to files modified after running `merged_data.py`, keeping relevant additions contributing to the addition of the new Scottish Forestry data source only._

## Screenshots (if appropriate):
Screenshot of dataframe when running the following code (filtered for new additions):

```python
source_arcgis = pd.DataFrame()
folder = "data/arcgis/"
for dirname, _, filenames in os.walk(folder):
    for filename in filenames:
        if filename.rsplit(".", 1)[1] == "csv":
            source_arcgis = pd.concat(
                [
                    source_arcgis,
                    pd.read_csv(
                        folder + r"/" + filename, parse_dates=["DateUpdated"]
                    ),
                ]
            )
source_arcgis["Source"] = "arcgis API"
```

image

## Types of changes

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x]  My code follows the code style of this project.
- [ ]  My change requires a change to the documentation.
- [ ]  I have updated the documentation accordingly.
- [ ]  I have read the **CONTRIBUTING** document.
- [x]  I have added tests to cover my changes.
- [ ]  All new and existing tests passed.

### CODE REVIEW

**Comment by marccodess** [comment]
I am unable to add a reviewer to this PR. 

@KarenJewell / @JackGilmore you seem to be the primary contributors to this project, just tagging you to make you aware of this contribution. Thank you.

**Comment by JackGilmore** [comment]
Thanks @marccodess. I've added myself and @KarenJewell as reviewers. Hopefully one of us can have a look this sometime this week 😊

**Comment by KarenJewell** [comment]
Thanks for this, looks magic to me! 
Ran arcgis.py, merge_data.py and export2jkan.py and all held up - happy to merge.

Just curious @marccodess how did you find navigating the project/docs? What could we improve?

**Comment by marccodess** [comment]
Thanks @KarenJewell, some feedback below:

Navigating the project wasn't too difficult, a suggestion would be to create a main.py script that allows the user to better understand the flow of the pipeline. I had to have a little look around first to get an idea of the order in which the scripts needed to be run.

A CONTRIBUTING.md file could be beneficial to create a standard process for contributing as well as any testing required depending on the area of the project you're contributing to.

Including docstrings on your classes/functions can also help when picking up the project for the first time.

Looking forward to contributing more in the future!

**Pull request merged**
